### ISSUE TITLE
Show a progress bar

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/bigrquery#100]
e.g., Gábor's [progress](https://cran.r-project.org/web/packages/progress/index.html) package.

**Comment by BrianWeinstein** [comment]
Would this go in the `list_tabledata_callback` function ([here](https://github.com/rstats-db/bigrquery/blob/178566458f701067f58942a5fd2ac3b863866ff6/R/tabledata.r#L83)) (using the `rows_fetched` and `last_response$totalRows` values)?

If so, we'd have to add the `last_response$totalRows` to the list returned by `list_tabledata_iter` [here](https://github.com/rstats-db/bigrquery/blob/178566458f701067f58942a5fd2ac3b863866ff6/R/tabledata.r#L162).
