### ISSUE TITLE
Integrate `list_tabledata_iter()` with BigQuery R6 class

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/bigrquery#105]
There are some redundancies which should be avoided.
- [ ] Un-export `list_tabledata_iter()`
- [ ] Add missing parts from _iter() to BigQuery class (if any)
- [ ] Use BigQuery R6 class internally
- [ ] Document and export BigQuery class + constructor

**Comment by hadley** [comment]
There doesn't seem to be an R6 class any more
