### ISSUE TITLE
Cannot retrieve more than 100k rows via dplyr+bigrquery

### ISSUE THREAD

**Issue by madcule** [rstats-db/bigrquery#113]
If a dplyr/bigrquery query returns more than 100k rows, the result is truncated with the warning:
"Only first 10 pages of size 10000 retrieved. Use max_pages = Inf to retrieve all."

It doesn't seem possible to set either max_pages or page_size via the dplyr/bigrquery interface (although it is possible to set max_pages via bigrquery::query_exec).

The following simple query will give this result if TableName has >100k rows.
```
db <- src_bigquery("project-id", "dataset-id")
table <- db %>% tbl("TableName")
bigData <- table %>% select(field) %>% collect()
```

It would be great if you could set a default max_pages for the connection, or set it for a query via the dplyr interface.

**Comment by craigcitro** [comment]
This should be fixed by #115. Thanks @davidadamsphd and @madcule!
