### ISSUE TITLE
Requires explicitly setting bigquery.quiet option

### ISSUE THREAD

**Issue by aalamWeddingWire** [rstats-db/bigrquery#114]
Running a query like so:

`bigrquery::query_exec(my_query, myroject = myporoject)`

raises the error:

```
Error in if (!is_quiet()) { : missing value where TRUE/FALSE needed In addition: 

Warning message:
In is.na(quiet) : is.na() applied to non-(list or vector) of type 'NULL'
```

Workaround is setting
`options(bigquery.quiet = NA)`

**Comment by hadley** [comment]
It works for me - the onload script sets a default value.
