### ISSUE TITLE
Dangerous bug with `filter` sql translations

### ISSUE THREAD

**Issue by realAkhmed** [rstats-db/bigrquery#120]
Hello everyone! It is great to see that `bigrquery` is getting under developers' spotlight again! 
If you don't mind I will be rolling out some of the issues that I ran into (some are pretty dangerous) over the year of working with it in my personal fork.

Below is the first dangerous bug.

``` r
library(dplyr)
library(bigrquery)

BILLING_PROJECT <- "<YOUR_BILLING_PROJECT>"
BILLING_DATASET <- "<DATASET_INSIDE_THAT_PROJECT>"

bq <- src_bigquery(BILLING_PROJECT, BILLING_DATASET)

# Upload the simple test data frame to your project
df <- data.frame(a = 1:100, b = 1:100)

bq_df <- copy_to(bq, df, name = "bq_df")

bq_df %>%
  filter(a == 1L | a== 2L) %>%
  filter(b == 100L) %>% 
  explain
```

It appears that two consecutive `filter`s produce an incorrect logical expression:

``` sql
<SQL>
SELECT [a], [b]
FROM [bq_df]
WHERE [a] = 1 OR [a] = 2 AND [b] = 100
```

Indeed, the code will report 1 incorrect record back

``` r
bq_df %>%
  filter(a == 1L | a== 2L) %>%
  filter(b == 100L) %>%
  collect()
```

which gives us

``` r
Source: local data frame [1 x 2]
      a     b
  (int) (int)
1     1     1
```

While using regular data frames:

``` r
df %>%
  filter(a == 1L | a== 2L) %>%
  filter(b == 100L)
```

the answer is correct:

``` r
[1] a b
<0 rows> (or 0-length row.names)
```

I think I solved it by requiring a collapse after every `filter` in the same spirit as #55.

If this is considered an acceptable solution, I can submit a pull request similar to #55 fixing it.

**Comment by hadley** [comment]
This should be fixed in dbplyr.
