### ISSUE TITLE
Authentication Failure in Jupyter Notebook

### ISSUE THREAD

**Issue by leggitta** [rstats-db/bigrquery#122]
I'm able to access my database and run a query when running R console, but when I try to do the same in a jupyter notebook, I get the following error ...

<img width="708" alt="screen shot 2016-06-24 at 8 35 36 am" src="https://cloud.githubusercontent.com/assets/1099867/16342382/ac69f7d0-39e6-11e6-998d-0d8e22c8ffab.png">

Is there a workaround for this?

**Comment by realAkhmed** [comment]
You need to copy `.httr-oauth` file to the current working directory.

The error means that:
* there is no authentication token available, and
* the system can't ask the user for a token since it isn't running in interactive mode

**Comment by leggitta** [comment]
Yup, that fixed it, thanks!

**Comment by pcejrowski** [comment]
The propsed solution is rather a workaround. Is there any proper way of authentication within Jupyter?

**Comment by CarreauClement** [comment]
Also looking for a cleaner solution ! Isn't it possible to use the GOOGLE_APPLICATION_CREDENTIALS variable to authenticate ?
