### ISSUE TITLE
prospects for simple authentication?

### ISSUE THREAD

**Issue by vjcitn** [rstats-db/bigrquery#123]
It would be really nice to encapsulate the authentication
event in a function that can be called with some simple arguments.  If we want to know that the user has a given google identity, could we not query for a google authenticator value?  User would have to know the identity and possess the device at which the authenticator app gets a token, and then they pass that token to the session.

**Comment by byapparov** [comment]
Are there any plans to support this? Basically it would be great to have a way to authenticate on non-interactive server via values stored in env variable without an auth file.

**Comment by hadley** [comment]
Do you have a specific example of how this would work with the google auth API?

**Comment by byapparov** [comment]
I think it should be very similar to what I can see on googleAuthR:

```r
options("googleAuthR.client_id" = "YOUR_CLIENT_ID")
options("googleAuthR.client_secret" = "YOUR_CLIENT_SECRET")
```
I would set this to environment variables alongside the refresh token if that is possible.

**Comment by hadley** [comment]
But you don't need a client id and secret for bigrquery. They're already set inside the package.

**Comment by hadley** [comment]
The recommend way to log in on a non-interactive server is to use `set_service_token()`
