### ISSUE TITLE
run query using standard SQL

### ISSUE THREAD

**Issue by RoyalTS** [rstats-db/bigrquery#125]
This isn't so much a bug as a question I'm having a hard time figuring out:

How do I run a query using BigQuery's standard SQL instead of its legacy SQL dialect (see https://cloud.google.com/bigquery/sql-reference/enabling-standard-sql)?

**Comment by RoyalTS** [comment]
I gather this can't be done yet as per #117 .

**Comment by backlin** [comment]
Would be great if you could try my pull request and confirm that it is working.

**Comment by RoyalTS** [comment]
Yeah, that works for me. Thanks!

**Comment by aumdavis** [comment]
It looks like you found a way to run standard SQL rather than legacy SQL using bigrquery?  How do you do it?  Is there some setting I need to apply?  I can't find anything in the documentation regarding this option.  I'm trying to run a query using a WITH clause and it's giving me an error due to applying the legacy SQL version.

**Comment by blakeyc** [comment]
Pass the option `useLegacySql = FALSE` through when you run `query_exec()`

For example
`results <- query_exec(sql, project = project, useLegacySql = FALSE)`

**Comment by craigcitro** [comment]
You can also use the `#standardSQL` prefix:
  https://cloud.google.com/bigquery/docs/reference/standard-sql/enabling-standard-sql

**Comment by aumdavis** [comment]
Thank you very  much craigcitro.  The #standardSQL prefix works great!  However, when I try to use the useLegacySql option in query_exec, it doesn't recognize it.

I tried reinstalling my bigrquery package in Rstudio, but when I look at the source code for the query_exec function, it doesn't have the useLegacySql option included.

Any suggestions on how I can get the updated bigrquery code to apply to my Rstudio session?

**Comment by hadley** [comment]
Further discussion to happen in #147

**Comment by craigcitro** [comment]
@aumdavis I suspect the issue is that the option you're looking for isn't in a CRAN release; if you need it, you can use `devtools::install_github` to install a newer version of bigrquery.

That said, if you're using the prefix, why do you need the `use_legacy_sql` option?

**Comment by aumdavis** [comment]
The prefix works so I'm happy. I just wanted to understand why my version
wasn't matching yours. Thanks for the explanation and all your excellent
help!
