### ISSUE TITLE
Error: Don't know how to convert type date

### ISSUE THREAD

**Issue by kmatt** [rstats-db/bigrquery#128]
Querying a simple table containing a date types column with SELECT \* ... LIMIT 10 I get the error

```
library(bigrquery)
project <- "***" # put your project ID here
sql <- "select date_dt from test.table limit 10"
df <- query_exec(sql, project = project)

Error: Don't know how to convert type date
```

Selecting a subset of columns without the date column succeeds, and selecting only the date column generates the error.

**Comment by sibalder** [comment]
Same problem here. 
code: PARSE_DATE('%E4Y%m%d', _TABLE_SUFFIX)
Error: Don't know how to convert type datetime
