### ISSUE TITLE
Retrieving data never finishes

### ISSUE THREAD

**Issue by jennagreen** [rstats-db/bigrquery#131]
I am trying to pull data with query_exc(..., max_pages = Inf), but the "Retrieving data: ..." part takes forever and never actually finishes. I looked at the query in BQ and the results are 3 million rows and 914MB table size which doesn't seem that big. Is there an additional argument I should be passing, or a better way to get the data?

bq_data = query_exec(sql, project = project, destination_table = "folder.test4", max_pages = Inf)

**Comment by shanFitGit** [comment]
I am facing the same issue.

**Comment by hadley** [comment]
Could you please provide a reproducible example? I realise this might be quite a lot of work, but otherwise there's no way for me to figure out what's wrong.

**Comment by hadley** [comment]
I'm going to close for now — I've added a progress bar so it should be easier to tell how long it's going to take, and I'll be making some more changes in the near future to make the whole process much faster.
