### ISSUE TITLE
"Encountered an error while globbing file pattern." In R while querying from google drive	

### ISSUE THREAD

**Issue by benjaminhaley** [rstats-db/bigrquery#132]
Can't query a google sheet that's linked to bigquery.

**What steps will reproduce the problem?**
1. Install bigrquery in R.
2. [Create a bigquery table from a google sheet][a]
3. Query that table in R:

```
query_exec(
    "SELECT` * FROM [khanacademy.org:deductive-jet-827:ben5.nyc_pilot_raw]", 
    project = "khanacademy.org:deductive-jet-827"
)
```

**What is the expected output? What do you see instead?**
Expect to get a table of results. That's what I get if I run the same query on the bigquery web UI. 
Instead I get `"Encountered an error while globbing file pattern."`

**What version of the product are you using? On what operating system?**
R version 3.3.1
Mac
latest bigrquery 

**Please provide any additional information below.**
I already tried running:
gcloud components update
gcloud auth login --enable-gdrive-access

Also posted this in the bigquery issue tracker
https://code.google.com/p/google-bigquery/issues/detail?id=755&thanks=755&ts=1477527760

[a]: https://cloud.google.com/blog/big-data/2016/05/bigquery-integrates-with-google-drive

**Comment by benjaminhaley** [comment]
Followup the folks on the bigquery issue tracker followed up. Sounds like bigrquery does not pass the correct permissions to do this:

> I checked our job log, and the detailed message says "No suitable credentials found to perform google drive request.".

see: https://code.google.com/p/google-bigquery/issues/detail?id=755#makechanges

**Comment by DrChrisLevy** [comment]
did anyone find a fix for this?

**Comment by hadley** [comment]
I see 

```R
list_tabledata(project, "sampledata", "sheet")
#> Error: Cannot list a table of type EXTERNAL. 
```

**Comment by hadley** [comment]
Oh but with `query_exec()` I get:

```R
query_exec("SELECT * FROM sampledata.sheet", project)
#> Error: Access Denied: BigQuery BigQuery: Permission denied while globbing file pattern. 
```

**Comment by hadley** [comment]
The [docs](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/insert#auth) suggest we more access permissions:

* htttps://www.googleapis.com/auth/bigquery
* https://www.googleapis.com/auth/cloud-platform
* https://www.googleapis.com/auth/devstorage.read_only
* https://www.googleapis.com/auth/devstorage.read_write
* https://www.googleapis.com/auth/devstorage.full_control

@craigcitro I assume it would make sense to request the first three?

**Comment by hadley** [comment]
That said, we are already requesting the first two, and the last three don't seem related to drive.

**Comment by craigcitro** [comment]
Actually `cloud-platform` implies all the others; note the "at least one" in the docs.

If we also want to access google sheets, we'd need to add https://www.googleapis.com/auth/drive, or at least https://www.googleapis.com/auth/drive.readonly. We should think about this one a bit, because that's a significant scope to request. (Maybe a new "think about scopes" issue is warranted.)

**Comment by hadley** [comment]
Yeah, that is significant.  For now, I'd say this is out of scope for bigrquery — unfortunately we have a lot of higher priority issues and only a relatively small amount of time to tackle them.

**Comment by DrChrisLevy** [comment]
Hey @hadley and @craigcitro , totally understand. Keep up the awesome work.

**Comment by kbmorales** [comment]
Just re-upping this. Despite loading an object that exists on Drive entirely into bigquery, the files maintains some sort of linkage, and bigrquery is unable to access these tables.
