### ISSUE TITLE
default to useLegacySql = NULL, instead of useLegacySql = TRUE

### ISSUE THREAD

**Issue by fhoffa** [rstats-db/bigrquery#134]
https://github.com/rstats-db/bigrquery/commit/9c539c779ba76049d2d8f6da2bdb5edfd4d02c2d

#standardSQL as a header will make your queries work as standard, without specifying it

but if it is specified, then the query fails

For example, the tool Exploratory.io that relies on bigrquery started failing my queries when bigrquery got this path.

Can we have useLegacySql default to NULL for most library users, except for those that want to explicitly use standard?

Test:

#standardSQL
select COUNT(*)
from `fh-bigquery.public_dump.numbers_255`

(this should work when useLegacySql=NULL, and fail if the #standardSQL header is removed)

**Comment by hadley** [comment]
Now part of #147
