### ISSUE TITLE
Unrecognized function timestamp_diff

### ISSUE THREAD

**Issue by abeburnett** [rstats-db/bigrquery#135]
Hi there, I'm getting the following error:

> Error: 8.24 - 8.90: Unrecognized function timestamp_diff

From running the following code:

```
library(bigrquery)

project <- "public-data-XXXXXX"

sql <- "
        SELECT User_Tenure,
                COUNT(1) AS Num_Users,
                ROUND(AVG(reputation)) AS Avg_Reputation,
                ROUND(AVG(num_badges)) AS Avg_Num_Badges
        FROM (
          SELECT users.id AS user,
                  ROUND(TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), ANY_VALUE(users.creation_date), DAY)/365) AS user_tenure,
                  ANY_VALUE(users.reputation) AS reputation,
                  SUM(IF(badges.user_id IS NULL, 0, 1)) AS num_badges
          FROM `bigquery-public-data.stackoverflow.users` AS users
          LEFT JOIN `bigquery-public-data.stackoverflow.badges` AS badges
          ON users.id = badges.user_id
          GROUP BY user
          )
          GROUP BY User_Tenure
          ORDER BY User_Tenure
"

so.tags <- query_exec(sql, project = project)
```

Other BigQuery queries are running fine, any idea what's throwing this one? It runs fine through the BigQuery UI...

Thanks!

**Comment by craigcitro** [comment]
Sorry for the slow reply -- I think the issue is that you need to set `useLegacySql = FALSE` as an argument to `query_exec`.

**Comment by abeburnett** [comment]
Ah. Gotcha. As a note for those who come across this later: at this point you'll need to ensure you grab the master branch explicitly from GitHub when you install. The code which is installed by default doesn't recognize the "useLegacySql" parameter. So you'll need to pass the `ref` = "master" parameter at the end of your devtools::install_github call.
