### ISSUE TITLE
seems like datetime is not supported now

### ISSUE THREAD

**Issue by inkrement** [rstats-db/bigrquery#140]
I don't know if this is a dplyr problem or bigrquery, but it is not possible to work with datetime-fields

```
tbl(src_bigquery("someproject", "dataset"), "tablewithdatetimefield")
```

> Error: Don't know how to convert type datetime

**Comment by kmatt** [comment]
https://github.com/rstats-db/bigrquery/pull/129

**Comment by inkrement** [comment]
Oh, thanks for the pull request! I tried to install it like this:

```
devtools::install_github("rstats-db/bigrquery#129", force= TRUE)
```

But I still get the same error. Did I forget something?

**Comment by hadley** [comment]
Duplicate of #128
