### ISSUE TITLE
Error: Reference a SQL view in a Legacy SQL query

### ISSUE THREAD

**Issue by sibalder** [rstats-db/bigrquery#142]
Can I somehow select 'Standard SQL' when using this package?

**Comment by blakeyc** [comment]
Simply pass through `useLegacySql = FALSE` when you execute the query.

**Comment by sibalder** [comment]
Thanks, but this function is not recognized?

Error in query_exec(sql, project, destination_table = NULL, default_dataset = NULL,  : 
  unused argument (useLegacySql = FALSE)

**Comment by blakeyc** [comment]
Sorry forgot, you need to install the package from github instead of the usual package manager. Using `devtools::install_github("rstats-db/bigrquery")` make sure you have the package `devtools` installed first.

Hope that helps.

**Comment by sibalder** [comment]
Thanks, will try that after the weekend and confirm!
