### ISSUE TITLE
Bigrquery join uses unsupported `USING` when join is on matching column name

### ISSUE THREAD

**Issue by seandavi** [rstats-db/bigrquery#146]
In short, bigquery does not support "USING" with a single field.  However, on my Mac system, that is the code that is getting generated by `left_join` when a single matching column is used for the join (like `by = c('url' = 'url')`).

I put together a quick example here using a public dataset.  Output is also included.

https://gist.github.com/f8edbdb2676259b63863c7387afc6e0a

This might very well be a local issue, but I cannot seem to track it down.

**Comment by hadley** [comment]
This will be fixed with dbplyr substantially reworks join SQL generation
