### ISSUE TITLE
Error: Error encountered during execution. Retrying may solve the problem.

### ISSUE THREAD

**Issue by dcabanillas** [rstats-db/bigrquery#154]
The sentence result<-query_exec(sql, project = project,max_pages = Inf)  sometimes gets me the following error  Error: Error encountered during execution. Retrying may solve the problem.  I think that could be related to http://stackoverflow.com/questions/36471938/started-to-get-error-503-when-streaming-data-to-bigquery

Any help to solve this issue? Perhaps to include a try-catch in my code.

Best.

**Comment by hadley** [comment]
Rather than using `query_exec()` you might want to call `insert_query_job()`, `wait_for()`, and `list_tabledata()` yourself so you have finer control and easier recovery.
