### ISSUE TITLE
Use Higher Tier

### ISSUE THREAD

**Issue by bkmrkr** [rstats-db/bigrquery#157]
When running a large query_exec I a message need higher Tier, is there a way to set this value directly from R?

Maximum Billing Tier   
Project Default

**Comment by craigcitro** [comment]
`query_exec` and friends will now pass through `...` as part of the request, so if you're using the development version, you can simply include the additional arguments in the API. (`snake_case` arguments will also be converted to the appropriate `camelCase` versions.)

https://github.com/rstats-db/bigrquery/commit/2bd7c72766895542b29a184ca9fc7bf605833891 for more details.
