### ISSUE TITLE
Cannot authenticate with BigQuery from RStudio running on a Google Compute Engine

### ISSUE THREAD

**Issue by ned2** [rstats-db/bigrquery#161]
I'm running RStudio on a Google Cloud Compute engine and struggling to authenticate with BigQuery.

More specifically, once I click 'Allow' from Google's authentication page, I'm redirected to localhost:1410, which is obviously not helpful as it's running on a remote machine not my local machine. I tried configuring the callback URL to be the IP address of the compute engine as per [this issue from httr](https://github.com/hadley/httr/issues/43) however Google's OAuth doesn't seem to like raw IP addresses apparently.

As a clunky workaround I created an SSH tunnel from localhost:1410 to my remote machine on the appropriate port, and this does redirect me back to the RStudio server, however nothing happens, and the previous command is still reporting "Waiting for authentication in browser..."

Perhaps I'm missing something obvious? This seems like a fairly standard setup.

**Comment by BrianWeinstein** [comment]
Instead of using OAuth, you might want to try [creating a service token](https://console.cloud.google.com/apis/credentials) and authenticating via the `set_service_token` function.

**Comment by ned2** [comment]
Yep, you're right. I came to the conclusion that this would be the best way to proceed after doing a bit more digging. Thanks for confirming that this is the way to go. 

It wasn't at all straightforward to work this out though. The [Google Cloud page on using BigQuery with R](https://twitter.com/elonmusk/status/869971423455924224) simply points you in the direction of the authentication section of bigrquery's README and that only refers to the OAuth. So it's not even clear there exists a programmatic way of authenticating unto you go and do some digging.

**Comment by hadley** [comment]
In the future we'll use gargle for auth, which will have more docs and support more auth mechanisms (#167)

**Comment by ras44** [comment]
@ned2 Another solution that does not require creating a service token is described [here](https://stackoverflow.com/questions/33168363/authorization-for-accessing-bigquery-from-r-session-on-server)  Both solutions mentioned work on GCE.
