### ISSUE TITLE
Use Google Cloud SDK config authentication

### ISSUE THREAD

**Issue by jpvelez** [rstats-db/bigrquery#162]
Greetings!

I'm trying to get bigrquery working for data scientists at Spotify, inside of a docker image. Here are the constraints:

- Folks love notebooks, so interactive authentication flow is out
- Per company policy, all data queries must executed by individual, so using a service account with `set_service_token(path)` is out

Many other tools and APIs that interact with GCP use Google Cloud SDK credentials. You "login" from the command line, triggering an interactive oauth flow similar to the one in bigrquery.

`gcloud auth login`

You can then see the active account with:
`gcloud config list`

1. Would it be possible for bigrquery to check for authentication here before asking for an interactive flow? This would mirror the behavior that many of google's own tools follow. (I believe the credentials are stored in ~/.config/gcloud/)

2. Some tools only work with application default credentials. That's typically the way you tell an application to use a service account in product. But you can also use it locally - with your personal account instead of a service account. You just do

`gcloud auth application-default login`

and go through the usual flow. This generates a json file in `~/.config/gcloud/application_default_credentials.json`. I tried using that with `set_service_token(path)`, but the json key is in a different format than the service account keys use.

Assuming this is a good idea, I'd be happy to hack on this given some direction.

**Comment by craigcitro** [comment]
We've got some nascent support for application default credentials in https://github.com/r-pkgs/gargle; the ultimate plan is to use that for auth here. As a first step, would you be willing to try giving that library a spin? If you've already got ADC set up, it should be as easy as `gargle::fetch_token('https://www.googleapis.com/auth/cloud-platform')`; if that reaches the point of trying to do the oauth2 browser dance, it means something didn't work. 😉

**Comment by hadley** [comment]
Will be solved in #167

**Comment by jpvelez** [comment]
Awesome! Thanks very much.

**Comment by bbhoss** [comment]
Is this possible currently?

**Comment by jpryda** [comment]
Got this working by setting the `GOOGLE_APPLICATION_CREDENTIALS` environmental variable to the location of `application_default_credentials.json` and forcing the `as_header` parameter of the token object to take a non-null boolean value

```
token <- gargle::credentials_app_default("https://www.googleapis.com/auth/bigquery")
token$params$as_header <- TRUE
set_access_cred(token)
```
