### ISSUE TITLE
Current CRAN versions of bigrquery and dplyr incompatible

### ISSUE THREAD

**Issue by EricGoldsmith** [rstats-db/bigrquery#164]
The newest CRAN version of `dplyr` (v0.7.0, released yesterday) causes problems with the current CRAN version of `bigrquery` (v0.3.0). 

```
> library(bigrquery)
Error : object ‘src_desc’ is not exported by 'namespace:dplyr'
Error: package or namespace load failed for ‘bigrquery’
```

The fix is either:

a) don’t install new version of dplyr
b) install development version of `bigrquery` (currently 0.3.0.9000) via `devtools::install_github("rstats-db/bigrquery”)`

Is a new CRAN release of `bigrquery` imminent?

**Comment by minimaxir** [comment]
Can confirm issue.

**Comment by bulam** [comment]
Was also running into the same issue. Installing the development version fixed it. Thanks!

**Comment by hadley** [comment]
Yes I know about this and I'm working on a release.
