### ISSUE TITLE
Response too large

### ISSUE THREAD

**Issue by madlg1** [rstats-db/bigrquery#166]
Hi, 
I get an error when dealing with large datasets. I have adjusted max-page=inf, but I dont know how to set the alowLargeResults parameter within my R code. I know how to do that in the bigquery UI, but uysing the package i am a bit lost.

this is the error:

Error: Response too large to return. Consider setting allowLargeResults to true in your job configuration. For more details, see https://cloud.google.com/bigquery/querying-data#largequeryresults

regards,
miguel

**Comment by IronistM** [comment]
Have you set a destination table for your response? 

e.g `query_exec(sql, project = project, max_pages = Inf,
                   destination_table = "your-project:your-dataset.your-new-table")`

BTW, `allow large results` is `TRUE` by default (https://github.com/rstats-db/bigrquery/blob/08b79afcb9675bacd0277c61b81209bbdb76879e/R/job-query.R#L59)

**Comment by madlg1** [comment]
HI,
I just saw it is TRUE, good to know. I was trying to add the query to a dataframe (there is enought memory space for it)

ciao,
m

**Comment by heoa** [comment]
I get the same error with

`test<- dbGetQuery(con, sql, n = 10000, max_pages = Inf)`

which results to 1 page but the error about too large dataset, the intended number of pages is over 500 pages. 

**How can I load large dataset to R?**

**Comment by sanyam521** [comment]
@hadley Even I am getting the same error: Error: Requested Resource Too Large to Return [responseTooLarge] when I try to import a table of dimension 5000 905 into R from google bigquery. It works fine when the table size is 468 905 with the same code:

billing <- "project_id" 

con <- dbConnect(
  bigrquery::bigquery(),
  project = "project_id",
  dataset = "dataset_name",
  billing = billing,
  use_legacy_sql = FALSE,
  allowLargeResults = TRUE
)
project<- "project name"
sql<- "select * from `table_name`"
data <- dbGetQuery(con,sql,use_legacy_sql = FALSE)

**Comment by deflaux** [comment]
Try changing the `page_size` parameter to be much less than its default value. 

Sometimes we get error "responseTooLarge" because the size of a single page of results is too large. This can happen for tables with many, many columns. By decreasing the page size, a single page of results is now small enough to return. More detail here: https://github.com/r-dbi/bigrquery/pull/353

**Comment by sanyam521** [comment]
Thank you so much, I used the page_size=1000 parameter and it worked. Is there any limit to the size of the data set that can be imported to R from GBQ?

**Comment by deflaux** [comment]
Great! A lot of people hit this issue, and the goal of https://github.com/r-dbi/bigrquery/pull/353 is to help users realize how to address it in a client-specific way.

Regarding the limits, the details are on https://cloud.google.com/bigquery/quotas and see https://cloud.google.com/bigquery/docs/getting-support for clarifications.

One of the best things about BigQuery is that it can be used to do all sorts of computations on incredibly large amounts of data without needing to transfer the data locally. Take a look at the giant list of functions on the righthand side of https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators

Sometimes I will prototype something in R on a small amount of data, then reimplement it in BigQuery SQL and check that I get the same result, etc. Then run the BigQuery SQL on the full extent of the data.
