### ISSUE TITLE
change from integer to numeric conversion?

### ISSUE THREAD

**Issue by nkeriks** [rstats-db/bigrquery#35]
Since bigquery seems to like using unix timestamps in milliseconds (at least that's how we set it up, but also many of the bigquery time functions deal with msecs), and since R integers are limited to 32 bits (and since it's not 1970 anymore) I'm wondering if changing the conversion in extract_data to use as.numeric would be a good idea.

Part of the problem here is due to an inconsistency with how as.integer works. The man page states that:

> The answer will be ‘NA’ unless the coercion succeeds.  Real
> values larger in modulus than the largest integer are coerced to
> ‘NA’ (unlike S which gives the most extreme integer of the same
> sign). 

But it turns out that as.integer('1414040723000') returns 2^31 - 1 instead of NA (applying as.numeric first returns NA).

It seems like this is a problematic failure mode - if you see a column of NAs, you realize something failed, whereas a column of maxint is less clearly wrong.

Of course there are lots of workarounds - I was just surprised by this behavior.

**Comment by krlmlr** [comment]
Perhaps related: #98.

**Comment by hadley** [comment]
@nkeriks is there any way you could generate a simple example that demonstrates this problem?

**Comment by hadley** [comment]
Should be fixed now - its easy to see the problem when dealing with fractional seconds.
