### ISSUE TITLE
dplyr backend for BigQuery: Get resulting schema for a query before executing it

### ISSUE THREAD

**Issue by deflaux** [rstats-db/bigrquery#41]
Per @hadley, he was looking for a way to get the result schema for a particular query _prior_ to executing it.

Unfortunately the BigQuery API does not support this today.  Per advice from @fhoffa:
1. Filing a [feature request](https://code.google.com/p/google-bigquery/issues/entry?template=Feature%20Request) to the BigQuery team to support this cleanly would be most appreciated.
2. In the meantime, [table decorators](https://cloud.google.com/bigquery/table-decorators) can be used to _effectively_ run a query on zero bytes of data.  By adding @-1- to the end of the table name, it will access everything that has been loaded in the last millisecond.  _Note that if any data was actually loaded within the prior millisecond the result would operate over more than zero bytes, but this should do the trick the vast majority of the time._

**Comment by krlmlr** [comment]
I have found that the decorator `@-1--1` also works. However, I also suspect that it returns the data timestamped at "now - 1 ms": a test using `@mod-mod` where mod is the modification time of the table returned nonzero rows.

**Comment by hadley** [comment]
@deflaux @craigcitro any updates in the last 2 (!!) years?

**Comment by hadley** [comment]
Looks like we can now get from the `dryRun` statistics (e.g. #143) although I've now forgotten why we needed this.

**Comment by craigcitro** [comment]
@hadley IIRC, we were trying to figure out schemas for questions like "can I join these two tables".

**Comment by hadley** [comment]
The dplyr API doesn't seem to need this anymore, but it's useful to know that you can now do a dry run.
