### ISSUE TITLE
str_extract fails to convert to integer

### ISSUE THREAD

**Issue by danielecook** [rstats-db/bigrquery#48]
Hello - thanks for developing bigrquery it's been a fantastic help. I'm having an issue extracting data from a column containing comma separated data.

```
mutate(df , PL_REF = as.integer(str_extract(N2_PL,"([0-9]+),[0-9]+,[0-9]+")))
Source: bigquery [201573431837:bamsurgeon]
From: variants3 [?? x 31]
Filter: call_method != "jointtest" 

Error: Encountered " <STRING_LITERAL> "\'([0-9]+),[0-9]+,[0-9]+\' "" at line 1, column 368.
Was expecting:
    ")" ...


query invalidQuery. Encountered " <STRING_LITERAL> "\'([0-9]+),[0-9]+,[0-9]+\' "" at line 1, column 368.
Was expecting:
    ")" ...
```

I'm able to exectute a working query in bigquery directly as such:

```
SELECT INTEGER(PL_REF) AS PL_REF, INTEGER(PL_HET) AS PL_HET, POW(INTEGER(PL_ALT),10) AS PL_ALT FROM 
   (SELECT 
       REGEXP_EXTRACT([N2_PL], '([0-9]+),[0-9]+,[0-9]+') AS [PL_REF],
       REGEXP_EXTRACT([N2_PL], '[0-9]+,([0-9]+),[0-9]+') AS [PL_HET],
       REGEXP_EXTRACT([N2_PL], '[0-9]+,[0-9]+,([0-9]+)') AS [PL_ALT]
    FROM [bamsurgeon.variants3])
LIMIT 10
```

Also note the power function for the third variable (PL_ALT), I was only able to execute this directly as well. bigrquery doesn't recognize `**` or `^` from what I have seen, but does appear to recognize POW, although without being able to convert successfully to an integer it will not function.

Thanks!

**Comment by krlmlr** [comment]
The following should work:

```
df %>%
  mutate(PL_REF_CHR = str_extract(N2_PL,"([0-9]+),[0-9]+,[0-9]+")) %>%
  mutate(PL_REF = as.integer(PL_REF_CHR))
```

But I think your first variant should also work.

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/jennybc/reprex#what-is-a-reprex)", and follow the advice further down the page.

**Comment by hadley** [comment]
```R
library(dplyr)
library(bigrquery)

con <- DBI::dbConnect(dbi_driver(),
  project = "bigrquery-examples",
  dataset = "test"
)
DBI::dbWriteTable(con, "test", data.frame(x = "a123"))

test <- tbl(con, "test")
test %>% 
  mutate(y = as.integer(str_extract(x, "([0-9]+)"))) %>%
  show_query()

DBI::dbRemoveTable(con, "test")
```
