### ISSUE TITLE
list_tables() fails if there are views present

### ISSUE THREAD

**Issue by lefko2000** [rstats-db/bigrquery#50]
Hi,

The error:
"Error in rbind(deparse.level, ...) : 
  les nombres de colonnes des arguments ne correspondent pas" (~column number mismatch).

I runned the inner steps of the function. The line causing trouble is:
"do.call("rbind", lapply(data, as.data.frame, row.names = 1L))"

The data is list of vectors of different lenghts thus the list cant be bound to produce a dataset.
This line has no impact on the expected output of list_tables. Would it be possible to remove it?

Best

**Comment by krlmlr** [comment]
Can't replicate this issue, not even with an empty dataset (however, list_tables() should probably return character() instead of NULL in this case).

**Comment by fjospinas** [comment]
https://github.com/rstats-db/bigrquery/pull/138

**Comment by hadley** [comment]
Source of problem is a project that contains a view.
