### ISSUE TITLE
Unable to append data through query_exec

### ISSUE THREAD

**Issue by 3vivekb** [rstats-db/bigrquery#62]
I want to perform a query and grab a large amount of data from one table, then add it to another table that already contains data using R.

So if I select a table that already exists I get "Error: Already Exists: Table ic..."

In Bigquery what is happpening is we are 
1. Selecting a destination table
2. Writing if empty
While using the Bigquery Web console we can 
1. Selecting a destination table
2. Append to a table

Can we add this functionality to bigrquery's query_exec?  Is it available in the BigQuery API?  I imagine it gets complicated when the tables are different.

**Comment by craigcitro** [comment]
the BQ API definitely supports this. we just need to thread the right arguments into `query_exec`.

**Comment by 3vivekb** [comment]
I think we should also have the feature to not return data.  R is a pretty convenient way to prototype and execute operations in order.

**Comment by craigcitro** [comment]
sure -- that's just a call to `insert_query_job`, right?

**Comment by 3vivekb** [comment]
Oh ha.  Yea.  Hmm.  Maybe we should add all the features I suggested above to insert_query_job instead.

**Comment by craigcitro** [comment]
I think we probably want them both places.

And a note in the docs that says "If you only need to run a query without retrieving results, see `insert_query_job`".

**Comment by BrianWeinstein** [comment]
This would be super helpful.

As a (slow) workaround for the time being, you can download the results using `query_exec`, and then append to the desired table with `insert_upload_job`.
