### ISSUE TITLE
I input the wrong credential the first time running query_exec() in R

### ISSUE THREAD

**Issue by ls3756** [rstats-db/bigrquery#74]
How do I clear the wrong credential so that the query will re-prompt me to enter the right credential? I tried to start my AWS or computer... it all doesn't seem to clear the memory.  Many thanks!

**Comment by nathangoulding** [comment]
If I'm understanding your question correctly `bigrquery::set_access_cred(NULL)` should do the trick.

**Comment by craigcitro** [comment]
The problem here was that the credential was cached by default, so as @nathangoulding says, you have to unset it first or delete the cache, which is in `getOption("httr_oauth_cache")`.

Closing, but reopen if there's something else going on.

**Comment by divyangashah** [comment]
I have same issue. I have tried bigrquery::set_access_cred(NULL)  command. but, than also it gives same error.

**Comment by craigcitro** [comment]
@divyangashah did you delete the file pointed to by `getOption("httr_oauth_cache")`?

**Comment by nathangoulding** [comment]
@craigcitro Timing-wise, would you accept a PR here that clears creds in this situation or is [ropenscilabs/gauth](https://github.com/ropenscilabs/gauth) close?

**Comment by craigcitro** [comment]
Do you mean clears it on a call to `set_access_cred`? Seems like that would be a reasonable optional arg ...

**Comment by nathangoulding** [comment]
I guess I meant more if a response was `Invalid Credentials` it would clear any cached credentials in `bigrquery`, to match the work that was done in https://github.com/hadley/httr/pull/315.

**Comment by craigcitro** [comment]
Oh -- yeah, that sgtm.

**Comment by divyangashah** [comment]
@craigcitro getOption("httr_oauth_cache") gives result as TRUE. so, which file I need to remove?

**Comment by craigcitro** [comment]
Oops -- I forgot that was a flag and not the name of the cache file. It's `.httr-oauth`.

**Comment by divyangashah** [comment]
@craigcitro .httr-oauth is not in readable format

**Comment by divyangashah** [comment]
@craigcitro thank u very much. It solved problem by removing .httr-oaith file :+1:
