### ISSUE TITLE
Rethink argument naming

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/bigrquery#85]
project_id vs. project
dataset_id vs. dataset

To me, the _id suffix looks unnecessary, but stripping it everywhere might create incompatibilities.

**Comment by craigcitro** [comment]
If bigrquery existed in the abstract, i agree using just `project`, `dataset`, and `table` is a clean choice. However, in our case, I think it's worth matching the BQ API itself as closely as possible; this means we want either `project_id` and friends or `projectId` and friends.

Thoughts @hadley ?

**Comment by hadley** [comment]
I think it's worth considering if we should have a helper function that every function uses, like:

```R
table <- function(project_id, dataset_id, table_id) {
 ...
}
```

**Comment by krlmlr** [comment]
@hadley: This would help.

Thinking about it, I guess the best way is to use the `_id` suffix all over the place; thanks to partial matching of argument names, this is compatible with function declarations that now don't use the suffix.
